name: CI

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.13"

jobs:
  lint-format:
    name: Ruff Lint & Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: astral-sh/setup-uv@v6.1.0
        with:
          enable-cache: true

      - name: Create virtual environment
        run: uv venv

      - name: Install dev dependencies
        run: uv pip install --group dev

      - name: Run Ruff Lint
        run: uv run ruff check .

      - name: Run Ruff Format Check
        run: uv run ruff format --check .

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: astral-sh/setup-uv@v6.1.0
        with:
          enable-cache: true

      - name: Create virtual environment
        run: uv venv

      - name: Install dev dependencies
        run: uv pip install --group dev

      - name: Run Pytest
        run: uv run pytest

  gitleaks:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}